-- Neon Postgres Database Schema
-- Generated by neon-postgres-skill
-- Database: Todo Application

-- Enable UUID extension (optional, useful for distributed systems)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- TABLES
-- =============================================================================

-- Todos table
CREATE TABLE IF NOT EXISTS todos (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT FALSE,
    priority VARCHAR(20) CHECK (priority IN ('low', 'medium', 'high')),
    due_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add comments for documentation
COMMENT ON TABLE todos IS 'User todo items with priority and due dates';
COMMENT ON COLUMN todos.id IS 'Unique identifier for the todo';
COMMENT ON COLUMN todos.title IS 'Todo title (required, max 255 characters)';
COMMENT ON COLUMN todos.description IS 'Optional detailed description';
COMMENT ON COLUMN todos.completed IS 'Whether the todo is completed';
COMMENT ON COLUMN todos.priority IS 'Priority level: low, medium, high';
COMMENT ON COLUMN todos.due_date IS 'Optional due date for the todo';
COMMENT ON COLUMN todos.created_at IS 'Timestamp when the todo was created';
COMMENT ON COLUMN todos.updated_at IS 'Timestamp when the todo was last updated';

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Index for filtering by completion status
CREATE INDEX IF NOT EXISTS idx_todos_completed ON todos(completed);

-- Index for filtering by priority
CREATE INDEX IF NOT EXISTS idx_todos_priority ON todos(priority);

-- Index for sorting by creation date
CREATE INDEX IF NOT EXISTS idx_todos_created_at ON todos(created_at DESC);

-- Partial index for active todos with due dates
CREATE INDEX IF NOT EXISTS idx_todos_due_date
ON todos(due_date)
WHERE due_date IS NOT NULL AND completed = FALSE;

-- Composite index for common query pattern (completed + priority)
CREATE INDEX IF NOT EXISTS idx_todos_completed_priority ON todos(completed, priority);

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =============================================================================
-- TRIGGERS
-- =============================================================================

-- Trigger to update updated_at on every UPDATE
CREATE TRIGGER update_todos_updated_at
BEFORE UPDATE ON todos
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- SAMPLE DATA (Optional - comment out if not needed)
-- =============================================================================

-- Insert sample todos for testing
INSERT INTO todos (title, description, completed, priority, due_date)
VALUES
    ('Setup Neon Postgres', 'Create database and apply schema', true, 'high', NULL),
    ('Build FastAPI backend', 'Create REST API with CRUD endpoints', false, 'high', NOW() + INTERVAL '3 days'),
    ('Design Next.js frontend', 'Build responsive UI with Tailwind CSS', false, 'high', NOW() + INTERVAL '5 days'),
    ('Add authentication', 'Implement user authentication and authorization', false, 'medium', NOW() + INTERVAL '7 days'),
    ('Write documentation', 'Create comprehensive project documentation', false, 'medium', NOW() + INTERVAL '10 days'),
    ('Deploy to production', 'Deploy application to cloud platform', false, 'low', NOW() + INTERVAL '14 days')
ON CONFLICT DO NOTHING;

-- =============================================================================
-- VERIFICATION
-- =============================================================================

-- Verify table creation
DO $$
DECLARE
    table_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO table_count
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'todos';

    IF table_count > 0 THEN
        RAISE NOTICE '✅ Table "todos" created successfully';
    ELSE
        RAISE EXCEPTION '❌ Failed to create table "todos"';
    END IF;
END $$;

-- =============================================================================
-- SCHEMA COMPLETE
-- =============================================================================
